/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MultiSigWallet } from "./MultiSigWallet";
export type { PaymeMultiSigWallet } from "./PaymeMultiSigWallet";
