/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MultiSigWallet__factory } from "./MultiSigWallet__factory";
export { PaymeMultiSigWallet__factory } from "./PaymeMultiSigWallet__factory";
