/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PaymeToken__factory } from "./PaymeToken__factory";
export { PayMEToken__factory } from "./PayMEToken__factory";
