/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PaymeTokenCrowdsale__factory } from "./PaymeTokenCrowdsale__factory";
export { PaymeTokenVesting__factory } from "./PaymeTokenVesting__factory";
